name = "Spectra"
uuid = "391af1a9-06f1-59d3-8d21-0be089654739"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]
version = "0.1.0"

[deps]
DustExtinction = "fb44c06c-c62f-5397-83f5-69249e0a3c8e"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[compat]
Interpolations = "≥0.9.0"
UnitfulAstro = "≥0.2.0"
julia = "^1.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
